
target "ContactsKit_iOS", :exclusive => true do
  
  pod "ContactsKit", :path => "../"
  platform :ios, "7.0"

end


target "ContactsKit_OSX", :exclusive => true do
  
  pod "ContactsKit", :path => "../"
  platform :osx, "10.7"

end

target "ContactsKit_iOS_Tests", :exclusive => true do
  
  pod "ContactsKit", :path => "../"
  platform :ios, "7.0"

end

target "ContactsKit_iOS_Logic_Tests", :exclusive => true do
  
  pod "ContactsKit", :path => "../"
  platform :ios, "7.0"

end
