
target "ContactsKit_iOS" do
  
  pod "ContactsKit", :path => "../"
  platform :ios, "7.0"

end


target "ContactsKit_OSX" do
  
  pod "ContactsKit", :path => "../"
  platform :osx, "10.7"

end

target "ContactsKit_iOS_Logic_Tests" do
  
  pod "ContactsKit", :path => "../"
  platform :ios, "7.0"

end
